### ISSUE TITLE
CI: Create actions to test the jupyter tutorial

### ISSUE THREAD

**Issue by mickahell** [IceKhan13/purplecaffeine#47]
### What is the expected enhancement?

Create a CI in order to have _unittests_ for the jupyter tutorial.

Example of how to do that :
```yaml
    - name: Test notebook
      run: |
        python -m pip install jupyter nbconvert nbformat
        jupyter nbconvert --to notebook --execute docs/guides/*.ipynb --inplace
```
